name: pr-validation

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get bjw-s-bot token
        id: get-app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: ${{ steps.get-app-token.outputs.token }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.20.0"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          args: release --snapshot --skip-publish --clean

  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Get bjw-s-bot token
        id: get-app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.BJWS_APP_ID }}
          private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: ${{ steps.get-app-token.outputs.token }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ">=1.20.0"

      - name: Run Unit Tests
        run: go test -v ./...
